//
// Created by Laurens van Dam on 19/02/2018.
//

#ifndef PAIRHMM_SIMPLE_CONFIG_HPP
#define PAIRHMM_SIMPLE_CONFIG_HPP

#ifndef DEBUG_PRECISION
#define DEBUG_PRECISION 40
#endif // DEBUG_PRECISION

#endif //PAIRHMM_SIMPLE_CONFIG_HPP
